export enum RabbitMQ {
    UserQueue = 'users',
    ProductQueue = 'product',
    OrderQueue = 'orders',
  }
  export enum UserMSG {
    CREATE = 'CREATE_USER',
    CREATE_ADMIN = 'create_admin',
    FIND_ALL = 'FIND_USERS',
    FIND_ONE = 'FIND_USER',
    UPDATE = 'UPDATE_USER',
    DELETE = 'DELETE_USER',
    VALID_USER = 'VALID_USER',
  }
  export enum ProductMSG {
    CREATE_PRODUCT = 'CREATE_PRODUCT',
    UPDATE_PRODUCT = 'EDIT_PRODUCT',
    DELETE_PRODUCT = 'DELETE_PRODUCT',
    FIND_BY_USERNAME = 'GET_USERBYNAME',
    CREATE_USER_MSP = 'CREATE_USER',
    UPDATE_USER_MSP = 'EDIT_USER',
    DELETE_USER_MSP = 'DELETE_USER',
    VALID_USER = 'VALID_USER',
    FIND_ALL = "FIND_ALL",
    GET_PRODUCT = "GET_PRODUCT",
  }
  export enum OrderMSG {
    CREATE = 'CREATE_ORDER',
    FIND_ALL_OITEMS = 'GET_ALL_ORDER_ITEMS',
    FIND_ALL_ORDERS = 'GET_ALL_ORDERS',
    FIND_ONE = 'FIND_ORDER',
    UPDATE = 'UPDATE_ORDER',
    DELETE = 'DELETE_ORDER',
    CREATE_PRODUCT = 'CREATE_PRODUCT',
    GET_PRODUCT = "GET_PRODUCT",
    UPDATE_PRODUCT = 'EDIT_PRODUCT',
    DELETE_PRODUCT = 'DELETE_PRODUCT',
    CREATE_ORDER_ITEM = 'CREATE_ORDER_ITEM',
    CREATE_USER = 'CREATE_USER',
    UPDATE_STATUS_ORDER = 'UPDATE_ORDER_STATUS_BY_TABLE',
    FIND_OITEMSBYUSERID= 'GET_ORDER_ITEMSBYUSER',

  }